apiVersion: v1
kind: Service
metadata:
  name: php-demoapp-service
spec:
  type: NodePort
  selector:
    app: php-demoapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8085
        protocol: TCP